const categoriasDespesa = [
  {
    id: 1,
    name: 'Alimentação',
    color: '#E374A7',
    type: 'despesa',
  },
  {
    id: 2,
    name: 'Assinaturas e serviços',
    color: '#C771E5',
    type: 'despesa',
  },
  {
    id: 3,
    name: 'Bares e restaurantes',
    color: '#626592',
    type: 'despesa',
  },
  {
    id: 4,
    name: 'Casa',
    color: '#8193FF',
    type: 'despesa',
  },
  {
    id: 5,
    name: 'Compras',
    color: '#F67BFF',
    type: 'despesa',
  },
  {
    id: 6,
    name: 'Cuidados pessoais',
    color: '#FF676C',
    type: 'despesa',
  },
  {
    id: 7,
    name: 'Dívidas e empréstimos',
    color: '#FE6C6C',
    type: 'despesa',
  },
  {
    id: 8,
    name: 'Educação',
    color: '#6470BA',
    type: 'despesa',
  },
  {
    id: 9,
    name: 'Família e filhos',
    color: '#A7E88C',
    type: 'despesa',
  },
  {
    id: 10,
    name: 'Impostos e taxas',
    color: '#FD977D',
    type: 'despesa',
  },
  {
    id: 11,
    name: 'Investimentos',
    color: '#FF6FA0',
    type: 'despesa',
  },
  {
    id: 12,
    name: 'Lazer e hobbies',
    color: '#B9E74E',
    type: 'despesa',
  },
  {
    id: 13,
    name: 'Mercado',
    color: '#FE8973',
    type: 'despesa',
  },
  {
    id: 14,
    name: 'Outros',
    color: '#B3B3B3',
    type: 'despesa',
  },
  {
    id: 15,
    name: 'Pets',
    color: '#F3C16C',
    type: 'despesa',
  },
  {
    id: 16,
    name: 'Presentes e doações',
    color: '#6A6FFF',
    type: 'despesa',
  },
  {
    id: 17,
    name: 'Roupas',
    color: '#FF8258',
    type: 'despesa',
  },
  {
    id: 18,
    name: 'Saúde',
    color: '#73B3FF',
    type: 'despesa',
  },
  {
    id: 19,
    name: 'Trabalho',
    color: '#446EF4',
    type: 'despesa',
  },
  {
    id: 20,
    name: 'Transporte',
    color: '#52BBFF',
    type: 'despesa',
  },
  {
    id: 21,
    name: 'Viagem',
    color: '#FF6B6B',
    type: 'despesa',
  },
];

export default categoriasDespesa;
