const types = {
  FETCH_DRIVERS_REQUEST: 'LIST_DRIVERS_REQUEST',
  FETCH_DRIVERS_SUCCESS: 'LIST_DRIVERS_SUCCESS',

  FILTER_DRIVERS_REQUEST: 'FILTER_DRIVERS_REQUEST',
  FILTER_DRIVERS_SUCCESS: 'FILTER_DRIVERS_SUCCESS',

  FETCH_TRAVELS_REQUEST: 'LIST_TRAVELS_REQUEST',
  FETCH_TRAVELS_SUCCESS: 'LIST_TRAVELS_SUCCESS',

  FILTER_TRAVELS_BY_DRIVER_REQUEST: 'FILTER_TRAVELS_BY_DRIVER_REQUEST',
  FILTER_TRAVELS_BY_DRIVER_SUCCESS: 'FILTER_TRAVELS_BY_DRIVER_SUCCESS',

  CHANGE_THEME: 'CHANGE_THEME',
};

export default types;
